/*
 * vgp.c
 *
 * Valgrind output parser
 * 
 * This program will parse a log file generated by Valgrind and generate a
 * more human readable version. It will remove extraneous info like PIDs and
 * addresses. In addition, it will list the source for the offending C/C++
 * function with the line causing the issue highlighted.
 * 
 * BTW, I hacked this together in an afternoon. So, it's a bit ugly and doesn't
 * come with any guarantees. But, it doesn't require any silly language
 * interpreters (I'm looking at you python) so it's got that ;-)
 * 
 * Created: 04/01/2025
 * Author : john anderson
 *
 * Copyright (C) 2025 by John Anderson <racerxr650r@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */ 
#include "vgp.h"

// --- Configuration ---
AppConfig app_config = {.verbose = false,
                        .print_source = false,
                        .print_stack = false,
                        .print_leak_summary = false,
                        .log_file = NULL };


const char *USER_CODE_EXTENSIONS[] = { ".c", ".cpp", ".h", ".hpp", NULL };
const char *IGNORE_PATHS[] = { "/usr/", "/lib/", "vg_", NULL };
const char *ERROR_KEYWORDS[] = {
    "Invalid read", "Invalid write",
    "depends on uninitialised value",
    "Invalid free", "Mismatched free",
    "Source and destination overlap",
    "Invalid usage of address",
    NULL
};

// --- Function Pointers for mocking ---
int (*printF)(const char*, ...) = printf;
FILE* (*Fopen)(const char *pathname, const char *mode) = fopen;
bool (*find_function_start_and_brace)(FILE *file, const char *function_name, int target_line, int *out_def_line, int *out_brace_line) = find_function_start_and_brace_;
void (*print_function_body)(FILE *file, int start_print_line, int brace_start_line, int highlight_line) = print_function_body_;
void (*print_error_header)(const char *error_type, ParseState *state) = print_error_header_;
bool (*is_user_code_stack_trace)(const char *line) = is_user_code_stack_trace_;
char* (*get_function_name)(const char *line, char *newline) = get_function_name_;
bool (*extract_file_and_line)(const char *line, char *filename, char *function_name, int *line_number) = extract_file_and_line_;
void (*print_source_function)(const char *filename, const char *function_name, int line_number) = print_source_function_;
void (*process_stack_trace_line)(const char *line_content, ParseState *state) = process_stack_trace_line_;
void (*finalize_error_block)(ParseState *state) = finalize_error_block_;
void (*print_leak_summary_header)(void) = print_leak_summary_header_;
void (*print_leak_summary_line)(const char *line, const char *leak_type) = print_leak_summary_line_;
void (*print_final_error_summary)(const char *line, ParseState *state) = print_final_error_summary_;
void (*initialize_parse_state)(ParseState *state) = initialize_parse_state_;
char* (*strip_valgrind_pid_prefix)(char *line) = strip_valgrind_pid_prefix_;
void (*process_in_error_block)(const char *line_content, ParseState *state) = process_in_error_block_;
bool (*check_start_new_error)(const char *line_content, ParseState *state) = check_start_new_error_;
void (*process_summary_lines)(const char *line_content, ParseState *state) = process_summary_lines_;

// --- Helper Functions ---
// Checks if a line is likely part of a user code stack trace.
bool is_user_code_stack_trace_(const char *line)
{
    // Check for stack trace indentation
    if (strncmp(line, "   at ", 6) != 0 && strncmp(line, "   by ", 6) != 0)
    {
        return false;
    }

    // Check for user code file extensions
    bool found_user_extension = false;
    for (int i = 0; USER_CODE_EXTENSIONS[i] != NULL; ++i)
    {
        if (strstr(line, USER_CODE_EXTENSIONS[i]) != NULL)
        {
            found_user_extension = true;
            break;
        }
    }
    if (!found_user_extension)
    {
        return false;
    }

    // Check if the path should be ignored
    for (int i = 0; IGNORE_PATHS[i] != NULL; ++i)
    {
        if (strstr(line, IGNORE_PATHS[i]) != NULL)
        {
            return false;
        }
    }

    return true;
}

// Removes the Valgrind PID prefix from a line.
char *strip_valgrind_pid_prefix_(char *line)
{
    // Locate the first occurrence of "=="
    char *prefix_end = strstr(line, "==");
    if(prefix_end == NULL)  
        return line; // No prefix found, return original line
    prefix_end += 2; // Move past "=="

    // Skip whitespace after "=="
    while(isspace((unsigned char)*prefix_end))
        prefix_end++;

    // Check if the prefix is followed by digits
    if (isdigit((unsigned char)*prefix_end))
    {
        // Find the end of the digits
        while (isdigit((unsigned char)*prefix_end))
            prefix_end++;
    }
    else
        return line; // No digits found, return original line

    // Skip whitespace after digits
    while(isspace((unsigned char)*prefix_end))
        prefix_end++;

    // Check for "== " after the digits
    if (strncmp(prefix_end, "== ", 3) != 0)
        return line; // No "==" found, return original line
    prefix_end += 3; // Move past "=="

    // Skip whitespace after "=="
//    while(isspace((unsigned char)*prefix_end) || *prefix_end == '\n')
//        prefix_end++;

    return prefix_end; // Return pointer to the start of the message
}

// Get just the function name, filename, and line number from a Valgrind stack trace line
char *get_function_name_(const char *line, char *newline)
{
    char function[MAX_LINE_LENGTH] = "?";
    char filename[MAX_LINE_LENGTH] = "?";
    int line_number = 0;
    int length = strlen(line);
    
    sscanf(line,"%*s %*s %[^ ] (%[^:]:%d)",function, filename, &line_number);

    if(line_number)
        snprintf(newline,length,"%s(%s:%d)\n",function,basename(filename),line_number);
    else
        snprintf(newline,length,"?(?:0)\n");

    return(newline);
}

// Prints an error block header.
void print_error_header_(const char *error_type, ParseState *state)
{
    printF("----------------------------------------\n");
    printF("[ERROR #%d] ", ++state->error_count);
    if(error_type[strlen(error_type) - 1] == '\n')
        printF("%s", error_type);
    else
        printF("%s\n", error_type);
    if(app_config.print_stack || app_config.verbose)
        printF("Call Stack:\n");
}

// Prints a leak summary header.
void print_leak_summary_header_(void)
{
    printF("\n--- LEAK SUMMARY ---\n");
}

// Prints a leak summary line.
void print_leak_summary_line_(const char *line, const char *leak_type)
{
    int bytes = 0, blocks = 0;
    //if (sscanf(line, "%*[^:]: %d bytes in %d blocks", &bytes, &blocks) == 2)
    if (sscanf(line, "%*[^:]: %'d %*s %*s %'d", &bytes, &blocks) == 2)
    {
        printF("* %s: %d bytes in %d blocks\n", leak_type, bytes, blocks);
    }
    else
    {
        if(line[strlen(line) - 1] == '\n')
            printF("%s", line); // Print raw if parse fails
        else
            printF("%s\n", line); // Print raw if parse fails
    }
}

// Prints the final error count summary.
void print_final_error_summary_(const char *line, ParseState *state)
{
    int error_count = 0;
    //if (sscanf(line, "ERROR SUMMARY: %d errors", &error_count) == 1)
    if (sscanf(line, "%*[^:]: %'d", &error_count) == 1)
    {
        printF("\n--- FINAL COUNTS ---\n");
        printF("* Total Errors: %d\n", state->error_count);
        printF("* Possible Leaks: %d\n", error_count - state->error_count);
    }
    else
    {
        if(line[strlen(line) - 1] == '\n')
            printF("%s", line); // Print raw if parse fails
        else
            printF("%s\n", line); // Print raw if parse fails
    }
}

// Extracts the filename, function name, and line number from a stack trace line.
bool extract_file_and_line_(const char *line, char *filename, char *function_name, int *line_number)
{
    if(line == NULL || filename == NULL || function_name == NULL || line_number == NULL)
    {
        return false; // Invalid arguments
    }

    char temp_filename[MAX_LINE_LENGTH];
    char temp_function[MAX_LINE_LENGTH];
    // Attempt to parse the line with function name
    if (sscanf(line, "%*[^:]: %[^(]( %[^:]:%d)", temp_function, temp_filename, line_number) == 3)
    {
        char *filename_ptr = strtok(temp_filename, " \t"); // Remove leading whitespace
        filename_ptr = strtok(filename_ptr, " \t"); // Remove trailing whitespace
        strcpy(filename, filename_ptr);

        char *functionname_ptr = strtok(temp_function, " \t"); // Remove leading whitespace
        functionname_ptr = strtok(functionname_ptr, " \t"); // Remove trailing newline
        strcpy(function_name, functionname_ptr);
        return true;
    }
    // Attempt to parse the line without function name
    else if (sscanf(line, "%*[^:]: %[^:]:%d", temp_filename, line_number) == 2)
    {
        strcpy(filename, temp_filename); // Fallback if basename fails
        strcpy(function_name, ""); // No function name available
        return true;
    }
    // Attempt to parse a line without line number
    else if (sscanf(line, "%*[^:]: %[^(](in %[^)])", temp_function, temp_filename) == 2)
    {
        char *filename_ptr = strtok(temp_filename, " \t"); // Remove leading whitespace
        filename_ptr = strtok(filename_ptr, " \t"); // Remove trailing whitespace
        strcpy(filename, filename_ptr);

        char *functionname_ptr = strtok(temp_function, " \t"); // Remove leading whitespace
        functionname_ptr = strtok(functionname_ptr, " \t"); // Remove trailing newline
        strcpy(function_name, functionname_ptr);

        *line_number = 0; // No line number available
        return true;
    }
    return false;
}

// Checks if a character is valid in a function name.
bool is_valid_function_char(char c)
{
    return isalnum((unsigned char)c) || c == '_'; // Added unsigned char cast for safety
}

// Helper to find the line containing the function definition and the opening brace
// Returns true if found and target_line is potentially within this function.
bool find_function_start_and_brace_(FILE *file, const char *function_name, int target_line,
                                   int *out_def_line, int *out_brace_line)
{
    if(file == NULL || function_name == NULL || out_def_line == NULL || out_brace_line == NULL)
        return false; // Invalid arguments

    char line[MAX_SOURCE_LINE_LENGTH];
    int current_line = 1;
    int potential_def_line = -1;
    *out_def_line = -1;
    *out_brace_line = -1;
    bool function_name_found = false;

    rewind(file);
    while (fgets(line, sizeof(line), file) != NULL)
    {
        // If we haven't found the function name yet, look for it
        if (!function_name_found)
        {
            char potential_name[MAX_LINE_LENGTH] = "";
            char *paren_start = strchr(line, '(');
            if (paren_start != NULL)
            {
                char *name_end = paren_start - 1;
                // Skip trailing whitespace before parenthesis
                while (name_end >= line && isspace((unsigned char)*name_end)) {
                    name_end--;
                }
                char *name_start = name_end;
                 // Move backwards to find the start of the potential function name
                while (name_start >= line && is_valid_function_char(*name_start)) {
                    name_start--;
                }
                name_start++; // Move one forward to the actual start of the function name

                // Extract the potential function name if valid characters were found
                if (name_start <= name_end) {
                    int len = name_end - name_start + 1;
                    if (len < MAX_LINE_LENGTH) {
                        strncpy(potential_name, name_start, len);
                        potential_name[len] = '\0';

                        // Check if the extracted name matches the target function name
                        if (strcmp(potential_name, function_name) == 0)
                        {
                            function_name_found = true;
                            potential_def_line = current_line; // Found the line with name(...)
                        }
                    }
                }
            }
        }

        // If we found the function name line, look for the opening brace '{' on subsequent lines
        if (function_name_found)
        {
            if (strchr(line, '{') != NULL)
            {
                // Found the opening brace. Check if target line is plausible.
                // The target line must be at or after the definition line.
                if (target_line >= potential_def_line) {
                    *out_def_line = potential_def_line;
                    *out_brace_line = current_line; // Line containing the '{'
                    return true; // Found definition and opening brace
                } else {
                    // Target line is before this function definition line, reset search
                    // This might happen if there are multiple functions with the same name.
                    function_name_found = false;
                    potential_def_line = -1;
                }
            }
        }
        current_line++;
    }
    return false; // Reached EOF without finding suitable function/brace
}

// Helper to print the function body, tracking braces
void print_function_body_(FILE *file, int start_print_line, int brace_start_line, int highlight_line)
{
    if(file == NULL || start_print_line <= 0 || brace_start_line <= 0 || highlight_line < 0)
        return; // Invalid file pointer

    char line[MAX_SOURCE_LINE_LENGTH];
    int current_line = 1;
    int brace_count = 0;
    bool printing = false;
    bool brace_started = false; // Track if we've seen the first '{'
    bool highlight_error = false; // Track if the highlight line was printed

    // Check for invalid line numbers
    rewind(file);
    while (fgets(line, sizeof(line), file) != NULL)
    {
        if (current_line == start_print_line)
            printing = true;
        if (current_line == brace_start_line)
            brace_started = true;
        if(current_line == highlight_line && !printing)
            highlight_error = true;
        if(brace_started)
        {
            for (int i = 0; line[i] != '\0'; i++)
            {
                if (line[i] == '{')
                    brace_count++;
                else if (line[i] == '}')
                    brace_count--;
            }
            if(brace_count == 0)
                break;
        }
        ++current_line;
    }

    if(!printing || !brace_started || highlight_error)
        return; // Nothing to print

    current_line = 1; // Reset line number for printing
    brace_count = 0; // Reset brace count
    brace_started = false; // Reset brace tracking
    printing = false; // Reset printing flag

    rewind(file);
    while (fgets(line, sizeof(line), file) != NULL)
    {
        // Start printing from the line where the function definition was found
        if (current_line >= start_print_line)
        {
            printing = true;
        }

        if (printing)
        {
            // Print line number, highlight marker, and line content
            printF("%c%4d%c %s",
                   (current_line == highlight_line) ? '>' : ' ',
                   current_line,
                   (current_line == highlight_line) ? '<' : ' ',
                   line);
            // Ensure newline if original line didn't have one (important for files without trailing newline)
            if (line[strlen(line)-1] != '\n') printF("\n");

            // Track braces only from the brace_start_line onwards to find the function end
            if (current_line >= brace_start_line) {
                 for (int i = 0; line[i] != '\0'; i++)
                 {
                     if (line[i] == '{')
                     {
                         if (!brace_started) brace_started = true;
                         brace_count++;
                     }
                     else if (line[i] == '}')
                     {
                         brace_count--;
                     }
                 }
                 // Stop printing after the line containing the final closing brace
                 // This handles cases where the closing brace is on the same line as other code.
                 if (brace_started && brace_count <= 0)
                 {
                     break;
                 }
            }
        }
        current_line++;

        // Safety break: Prevent excessively long printing if brace matching fails
        if (printing && current_line > start_print_line + 5000)
        {
             printF("\nWarning: Stopped printing function body after 5000 lines (possible brace mismatch in '%s'?)\n", "source file"); // Filename not available here easily
             break;
        }
    }
    if (brace_count > 0 && current_line <= start_print_line + 5000)
        printF("\nWarning: Reached EOF while printing function body, brace level indicates mismatch (%d).\n", brace_count);
}

// Prints the source code of the entire function containing the given line number.
void print_source_function_(const char *filename, const char *function_name, int line_number)
{
    // Handle case where function name might be empty
    if (function_name == NULL || function_name[0] == '\0') {
        // Use fprintf to stderr for warnings/errors
        printF("Warning: Cannot print source for line %d in '%s': Function name not extracted from Valgrind log.\n", line_number, filename);
        return;
    }
     if (line_number <= 0) {
        printF("Warning: Cannot print source for function '%s' in '%s': Invalid line number (%d) extracted.\n", function_name, filename, line_number);
        return;
    }

    FILE *source_file = Fopen(filename, "r");
    if (!source_file)
    {
        printF("Error: Failure opening source file '%s': %s\n", filename, strerror(errno));
        return;
    }

    int function_def_line = -1;
    int function_brace_line = -1;

    // Find the start of the function definition and its opening brace
    bool found = find_function_start_and_brace(source_file, function_name, line_number,
                                               &function_def_line, &function_brace_line);

    if (found)
    {
        // Print the function body
        print_function_body(source_file, function_def_line, function_brace_line, line_number);
    }
    else
    {
        // Provide a more specific warning based on whether the function name was found but the line number was outside,
        // or the function name itself wasn't found. (Current helper doesn't easily distinguish this, needs more state return)
        printF("Warning: Could not locate function '%s' near line %d in file '%s'.\n",
               function_name, line_number, filename);
        printF("         (Check if function name or line number from Valgrind log is correct and file wasn't modified.)\n");
    }

    fclose(source_file);
}

// --- Core Parsing Logic ---
// Initializes the parsing state
void initialize_parse_state_(ParseState *state)
{
    if(state != NULL)
    {
        state->in_error_block = false;
        state->print_function = false;
        state->stack_lines_shown = 0;
        state->user_code_found_for_error = false;
        state->current_error_type[0] = '\0';
        state->error_filename[0] = '\0';
        state->error_function_name[0] = '\0';
        state->error_line_number = -1;
        state->error_count = 0;
    }
}

// Checks if the line marks the start of a new error block
bool check_start_new_error_(const char *line_content, ParseState *state)
{
    if (line_content == NULL || state == NULL)
        return false; // Invalid arguments

    if (!state->in_error_block)
    {
        for (int i = 0; ERROR_KEYWORDS[i] != NULL; ++i)
        {
            if (strstr(line_content, ERROR_KEYWORDS[i]))
            {
                print_error_header(line_content, state);
                strncpy(state->current_error_type, ERROR_KEYWORDS[i], sizeof(state->current_error_type) - 1);
                state->current_error_type[sizeof(state->current_error_type) - 1] = '\0';
                state->in_error_block = true;
                state->stack_lines_shown = 0;
                state->user_code_found_for_error = false;
                state->print_function = false; // Reset print flag for new error
                return true; // New error detected
            }
        }
    }
    return false; // Not the start of a new error
}

// Processes a line identified as part of a stack trace
void process_stack_trace_line_(const char *line_content, ParseState *state)
{
    if(line_content == NULL || state == NULL)
        return; // Invalid arguments

    if (state->stack_lines_shown < STACK_TRACE_CONTEXT_LINES || is_user_code_stack_trace(line_content))
    {
        char stack_entry[MAX_LINE_LENGTH];
        if(app_config.print_stack || app_config.verbose)
        {
            printF("  - %s", get_function_name((const char*)line_content, stack_entry)); // Cast needed for get_function_name prototype
            state->stack_lines_shown++;
        }

        if (!state->user_code_found_for_error && is_user_code_stack_trace(line_content))
        {
            state->user_code_found_for_error = true;
            // Extract file/line and set flag to print source later
            state->print_function = extract_file_and_line(line_content, state->error_filename, state->error_function_name, &state->error_line_number);
        }
    }
    else if (!state->user_code_found_for_error && state->stack_lines_shown == STACK_TRACE_CONTEXT_LINES)
    {
        if(app_config.print_stack || app_config.verbose)
        {
            // Print ellipsis only once after context lines if no user code found yet
            printF("  - ...\n");
            state->stack_lines_shown++; // Increment to prevent printing ellipsis again
        }
    }
}

// Finalizes the processing of an error block (prints source, resets state)
void finalize_error_block_(ParseState *state)
{
    if (state == NULL)
        return; // Invalid arguments

    if (!state->user_code_found_for_error && state->stack_lines_shown > 0)
    {
        printF("  (-> Check stack trace above for user code related to '%s')\n", state->current_error_type);
    }
    if (state->print_function)
    {
        printF("Source (%s:%d)\n", state->error_filename, state->error_line_number);
        if(app_config.print_source || app_config.verbose)
        {
            print_source_function(state->error_filename, state->error_function_name, state->error_line_number);
            printF("\n");
        }
    }
    // Reset state for the next block (or end of file)
    state->in_error_block = false;
    state->print_function = false;
    // No need to print the separator here, let the next error header do it or handle at EOF.
}

// Processes lines within an active error block
void process_in_error_block_(const char *line_content, ParseState *state)
{
    if (line_content == NULL || state == NULL)
        return; // Invalid arguments
    
    if (strncmp(line_content, "   at ", 6) == 0 || strncmp(line_content, "   by ", 6) == 0)
    {
        process_stack_trace_line(line_content, state);
    }
    else
    {
        // Line is not a stack trace line, signifies end of the current error's stack trace
        finalize_error_block(state);
        // Note: We might need to re-process this line if it's a summary line or start of a new error
        // This refactoring assumes error blocks are separated by non-stack-trace lines or EOF.
    }
}

// Checks for and processes summary lines (Leak or Final)
void process_summary_lines_(const char *line_content, ParseState *state)
{
    if (line_content == NULL)
        return; // Invalid arguments

    if (strstr(line_content, "LEAK SUMMARY:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_header();
    }
    else if (strstr(line_content, "definitely lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Definitely Lost");
    }
    else if (strstr(line_content, "indirectly lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Indirectly Lost");
    }
    else if (strstr(line_content, "possibly lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Possibly Lost");
    }
    else if (strstr(line_content, "still reachable:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Still Reachable");
    }
    else if (strstr(line_content, "ERROR SUMMARY:"))
    {
        print_final_error_summary(line_content, state);
    }
}

// Processes the entire log file
void process_log_file(FILE *file)
{
    if (file == NULL)
        return; // Invalid file pointer

    char line[MAX_LINE_LENGTH];
    ParseState state;
    initialize_parse_state(&state);

    while (fgets(line, sizeof(line), file))
    {
        char *line_content = strip_valgrind_pid_prefix(line);

        // Skip empty or whitespace-only lines *unless* inside an error block
        // (empty lines can sometimes terminate an error block in Valgrind output)
        if (!state.in_error_block && strspn(line_content, " \t\n\r") == strlen(line_content))
        {
            continue;
        }

        // If we are in an error block, process the line accordingly
        if (state.in_error_block)
        {
            process_in_error_block(line_content, &state);
            // If finalize_error_block was called, state.in_error_block is now false.
            // We continue to the summary check below for the same line.
        }

        // Check if the line starts a *new* error block (only if not currently in one)
        // Or if the previous block was just finalized.
        if (!state.in_error_block)
        {
            bool new_error_started = check_start_new_error(line_content, &state);
            if (new_error_started)
            {
                continue; // Skip summary checks if it's the start of an error
            }
        }

        // Check for summary lines (Leak or Final) if not inside an error block
        if (!state.in_error_block)
        {
             process_summary_lines(line_content, &state);
        }
    }

    // Handle the case where the file ends while still inside an error block
    if (state.in_error_block)
    {
        finalize_error_block(&state); // Print source if needed
        printF("----------------------------------------\n\n"); // Add final separator
    }
}
