/*
 * vgp.c
 *
 * Valgrind output parser
 * 
 * This program will parse a log file generated by Valgrind and generate a
 * more human readable version. It will remove extraneous info like PIDs and
 * adresses. In addition, it will list the source for the offending C/C++
 * function with the line causing the issue highlighted.
 * 
 * BTW, I hacked this together in an afternoon. So, it's a bit ugly and doesn't
 * come with any guarantees. But, it doesn't require any silly language
 * interpreters (I'm looking at you python) so it's got that ;-)
 * 
 * Created: 04/01/2025
 * Author : john anderson
 *
 * Copyright (C) 2025 by John Anderson <racerxr650r@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */ 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h> // For errno and strerror
#include <libgen.h> // For basename
#include <ctype.h> // For isalnum, isspace

// --- Constants ---
#define MAX_LINE_LENGTH 2048
#define STACK_TRACE_CONTEXT_LINES 3
#define MAX_ERROR_TYPE_LENGTH 128
#define MAX_SOURCE_LINE_LENGTH 2048 // Maximum length of a line in the source file

// --- Configuration ---
const char *USER_CODE_EXTENSIONS[] = { ".c:", ".cpp:", ".h:", ".hpp:", NULL };
const char *IGNORE_PATHS[] = { "/usr/", "/lib/", "vg_", NULL };

// --- Helper Functions ---

// Checks if a line is likely part of a user code stack trace.
bool is_user_code_stack_trace(const char *line)
{
    // Check for stack trace indentation
    if (strncmp(line, "   at ", 6) != 0 && strncmp(line, "   by ", 6) != 0)
    {
        return false;
    }

    // Check for user code file extensions
    bool found_user_extension = false;
    for (int i = 0; USER_CODE_EXTENSIONS[i] != NULL; ++i)
    {
        if (strstr(line, USER_CODE_EXTENSIONS[i]) != NULL)
        {
            found_user_extension = true;
            break;
        }
    }
    if (!found_user_extension)
    {
        return false;
    }

    // Check if the path should be ignored
    for (int i = 0; IGNORE_PATHS[i] != NULL; ++i)
    {
        if (strstr(line, IGNORE_PATHS[i]) != NULL)
        {
            return false;
        }
    }

    return true;
}

// Removes the Valgrind PID prefix from a line.
char *strip_valgrind_pid_prefix(char *line)
{
    if (strncmp(line, "==", 2) == 0)
    {
        char *prefix_end = strstr(line, "== ");
        if (prefix_end)
        {
            return prefix_end + 3;
        }
        // Handle variation like ==PID==\n
        if (line[strlen(line) - 1] == '\n' && strstr(line, "==") == line + strlen(line) - 3)
        {
            return "";
        }
    }
    return line;
}

// Get just the function name and filename
char *get_function_name(char *line, char *newline)
{
    char function[MAX_LINE_LENGTH];
    char filename[MAX_LINE_LENGTH];
    int line_number;
    int length = strlen(line);
    
    sscanf(line,"%*s %*s %[^ ] (%[^:]:%d)",function, filename, &line_number);

    snprintf(newline,length,"%s(%s:%d)\n",function,basename(filename),line_number);
    return(newline);
}

// Prints an error block header.
void print_error_header(const char *error_type)
{
    printf("----------------------------------------\n");
    printf("[ERROR] %s", error_type);
    printf("----------------------------------------\n");
    printf("Call Stack:\n");
}

// Prints a leak summary header.
void print_leak_summary_header(void)
{
    printf("\n--- LEAK SUMMARY ---\n");
}

// Prints a leak summary line.
void print_leak_summary_line(const char *line, const char *leak_type)
{
    int bytes = 0, blocks = 0;
    if (sscanf(line, "%*[^:]: %d bytes in %d blocks", &bytes, &blocks) == 2)
    {
        printf("* %s: %d bytes in %d blocks\n", leak_type, bytes, blocks);
    }
    else
    {
        printf("%s", line); // Print raw if parse fails
    }
}

// Prints the final error count summary.
void print_final_error_summary(const char *line)
{
    printf("\n--- FINAL COUNTS ---\n");
    int error_count = 0;
    if (sscanf(line, "ERROR SUMMARY: %d errors", &error_count) == 1)
    {
        printf("* Total Errors Reported by Valgrind: %d\n", error_count);
    }
    else
    {
        printf("%s", line); // Print raw if parse fails
    }
}

// Extracts the filename, function name, and line number from a stack trace line.
bool extract_file_and_line(const char *line, char *filename, char *function_name, int *line_number)
{
    char temp_filename[MAX_LINE_LENGTH];
    char temp_function[MAX_LINE_LENGTH];
    // Attempt to parse the line with function name
    if (sscanf(line, "%*s %*s %[^ ] (%[^:]:%d)", temp_function, temp_filename, line_number) == 3)
    {
        // Extract only the filename (remove directory path)
//        char *base = basename(temp_filename);
//        if (base != NULL)
//        {
//            strcpy(filename, base);
//        }
//        else
//        {
            strcpy(filename, temp_filename); // Fallback if basename fails
//        }
        strcpy(function_name, temp_function);
        return true;
    }
    // Attempt to parse the line without function name
    else if (sscanf(line, "%*s %*s %[^:]:%d", temp_filename, line_number) == 2)
    {
        // Extract only the filename (remove directory path)
        char *base = basename(temp_filename);
        if (base != NULL)
        {
            strcpy(filename, base);
        }
        else
        {
            strcpy(filename, temp_filename); // Fallback if basename fails
        }
        strcpy(function_name, ""); // No function name available
        return true;
    }
    return false;
}

// Checks if a character is valid in a function name.
bool is_valid_function_char(char c)
{
    return isalnum(c) || c == '_' || c == '*';
}

// Prints the source code of the entire function containing the given line number.
void print_source_function(const char *filename, const char *function_name, int line_number)
{
    FILE *source_file = fopen(filename, "r");
    if (!source_file)
    {
        printf("Error opening source file '%s': %s\n", filename, strerror(errno));
        return;
    }

    char source_line[MAX_SOURCE_LINE_LENGTH];
    int current_line = 1;
    int start_line = -1;
    int brace_count = 0;
    bool found_function = false;
    char potential_function_name[MAX_LINE_LENGTH];
    int function_start_brace_line = -1;
    bool in_function = false;

    // First pass: Find the start of the function
    rewind(source_file);
    while (fgets(source_line, sizeof(source_line), source_file) != NULL)
    {
        // Reset potential function name
        potential_function_name[0] = '\0';

        // Look for a potential function definition
        char *paren_start = strchr(source_line, '(');
        if (paren_start != NULL)
        {
            char *before_paren = paren_start - 1;
            // Move backwards to find the end of the potential function name
            while (before_paren >= source_line && is_valid_function_char(*before_paren))
            {
                before_paren--;
            }
            before_paren++; // Move one forward to the start of the function name

            // Extract the potential function name
            if (before_paren > source_line)
            {
                int len = paren_start - before_paren;
                strncpy(potential_function_name, before_paren, len);
                potential_function_name[len] = '\0';

                // Check if the extracted name matches the target function name or if we don't have a target
                if (strlen(function_name) == 0 || strcmp(potential_function_name, function_name) == 0)
                {
                    found_function = true;
                    if (current_line <= line_number)
                    {
                        start_line = current_line;
                    }
                }
            }
        }
        if (found_function && start_line != -1)
        {
            if (strstr(source_line, "{") != NULL)
            {
                function_start_brace_line = current_line;
            }
        }
        if (function_start_brace_line != -1 && current_line >= function_start_brace_line)
        {
            in_function = true;
            for (int i = 0; source_line[i] != '\0'; i++)
            {
                if (source_line[i] == '{')
                {
                    brace_count++;
                }
                else if (source_line[i] == '}')
                {
                    brace_count--;
                }
            }
            if (brace_count == 0)
            {
                break;
            }
        }
        current_line++;
    }

    // Second pass: Print the function
    if (found_function && start_line != -1 && function_start_brace_line != -1 && line_number >= start_line)
    {
        rewind(source_file);
        current_line = 1;
        brace_count = 0;
        in_function = false;
        bool brace_start = false;
        while (fgets(source_line, sizeof(source_line), source_file) != NULL)
        {
            if (current_line >= start_line)
            {
                in_function = true;
            }
            if (in_function)
            {
                printf("%c%d%c%.71s",(current_line==line_number)?'<':' ',current_line,(current_line==line_number)?'>':' ',source_line);
                if(strlen(source_line)>=80)
                    printf("... \n");
                for (int i = 0; source_line[i] != '\0'; i++)
                {
                    if (source_line[i] == '{')
                    {
                        if(brace_start==false)
                            brace_start=true;
                        brace_count++;
                    }
                    else if (source_line[i] == '}')
                    {
                        brace_count--;
                    }
                }
                if (brace_start == true && brace_count == 0)
                {
                    break;
                }
            }
            current_line++;
        }
    }
    else
    {
        if (!found_function)
        {
            printf("Could not find function '%s' in '%s'\n", function_name, filename);
        }
        else
        {
            printf("Could not find function containing line %d in '%s'\n", line_number, filename);
        }
    }

    fclose(source_file);
}

// --- Main Logic ---

int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        printf("Usage: %s <valgrind_log_file>\n", argv[0]);
        printf("Parses a Valgrind log and shows the call stack and source code for the functions with errors.\n");
        return EXIT_FAILURE;
    }

    const char *filename = argv[1];

    FILE *file = fopen(filename, "r");
    if (!file)
    {
        perror("Error opening file");
        return EXIT_FAILURE;
    }

    printf("--- Valgrind Log Summary ---\n");
    printf("Parsing Log File: %s\n", filename);

    char line[MAX_LINE_LENGTH];
    bool in_error_block = false;
    bool print_function = false;
    int stack_lines_shown = 0;
    bool user_code_found_for_error = false;
    char current_error_type[MAX_ERROR_TYPE_LENGTH] = {0};

    const char *ERROR_KEYWORDS[] = {
        "Invalid read", "Invalid write",
        "depends on uninitialised value",
        "Invalid free", "Mismatched free",
        "Source and destination overlap",
        "Invalid usage of address",
        NULL
    };

    while (fgets(line, sizeof(line), file))
    {
        char *line_content = strip_valgrind_pid_prefix(line);
        char error_filename[MAX_LINE_LENGTH];
        char error_function_name[MAX_LINE_LENGTH];
        int error_line_number;

        // Skip empty or whitespace-only lines unless inside an error block
        if (!in_error_block && strspn(line_content, " \t\n\r") == strlen(line_content))
        {
            continue;
        }

        // Detect Start of a New Error Block
        bool new_error_detected = false;
        if (!in_error_block)
        {
            for (int i = 0; ERROR_KEYWORDS[i] != NULL; ++i)
            {
                if (strstr(line_content, ERROR_KEYWORDS[i]))
                {
                    print_error_header(line_content);
                    strncpy(current_error_type, ERROR_KEYWORDS[i], sizeof(current_error_type) - 1);
                    current_error_type[sizeof(current_error_type) - 1] = '\0';
                    in_error_block = true;
                    new_error_detected = true;
                    stack_lines_shown = 0;
                    user_code_found_for_error = false;
                    break;
                }
            }
        }

        // Process Lines Within an Error Block (Stack Traces)
        if (in_error_block && !new_error_detected)
        {
            if (strncmp(line_content, "   at ", 6) == 0 || strncmp(line_content, "   by ", 6) == 0)
            {
                if (stack_lines_shown < STACK_TRACE_CONTEXT_LINES || is_user_code_stack_trace(line_content))
                {
                    char stack_entry[MAX_LINE_LENGTH];
                    
                    printf("  - %s", get_function_name(line_content,stack_entry));
                    stack_lines_shown++;

                    if (!user_code_found_for_error && is_user_code_stack_trace(line_content))
                    {
                       //printf("  ^^^ User Code Location for '%s' Error ^^^\n", current_error_type);
                        user_code_found_for_error = true;
                        // Extract file and line number and print source code
                        print_function = extract_file_and_line(line_content, error_filename, error_function_name, &error_line_number);
                    }
                }
                else if (!user_code_found_for_error && stack_lines_shown >= STACK_TRACE_CONTEXT_LINES)
                {
                    // Maybe print an ellipsis once? (...)
                    printf("  - ...\n");
                }
            }
            else
            {
                if (!user_code_found_for_error && stack_lines_shown > 0)
                {
                    printf("  (-> Check stack trace above for user code related to '%s')\n", current_error_type);
                }
                if(print_function)
                {
                    printf("Source (%s):\n", error_filename);
                    print_source_function(error_filename, error_function_name, error_line_number);
                    printf("\n");
                    print_function = false;
                }
                //printf("----------------------------------------\n\n");
                in_error_block = false;
            }
        }

        // Detect and Parse Leak Summary Lines
        if (strstr(line_content, "LEAK SUMMARY:"))
        {
            print_leak_summary_header();
        }
        else if (strstr(line_content, "definitely lost:"))
        {
            print_leak_summary_line(line_content, "Definitely Lost");
        }
        else if (strstr(line_content, "indirectly lost:"))
        {
            print_leak_summary_line(line_content, "Indirectly Lost");
        }
        else if (strstr(line_content, "possibly lost:"))
        {
            print_leak_summary_line(line_content, "Possibly Lost");
        }
        else if (strstr(line_content, "still reachable:"))
        {
            print_leak_summary_line(line_content, "Still Reachable");
        }

        // Detect Final Error Count Summary
        if (strstr(line_content, "ERROR SUMMARY:"))
        {
            print_final_error_summary(line_content);
        }
    }

    // Handle error block at end of file
    if (in_error_block)
    {
        if (!user_code_found_for_error && stack_lines_shown > 0)
        {
            printf("  (-> Check stack trace above for user code related to '%s')\n", current_error_type);
        }
        printf("----------------------------------------\n\n");
    }

    fclose(file);
    printf("\n--- End of Summary ---\n");
    return EXIT_SUCCESS;
}
