/*
 * vgp.h
 *
 * Valgrind output parser header file
 * 
 * This program parses a log file generated by Valgrind and generates a
 * more human readable version. It removes extraneous info like PIDs and
 * absolute addresses. In addition, it lists the source code for the offending
 * C/C++ function with the line causing the issue highlighted.
 * 
 * Created: 04/01/2025
 * Author : john anderson
 *
 * Copyright (C) 2025 by John Anderson <racerxr650r@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef VGP_H
#define VGP_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h> // For errno and strerror
#include <libgen.h> // For basename
#include <ctype.h> // For isalnum, isspace
#include <locale.h> // For setlocale

 // --- Constants ---
#define MAX_LINE_LENGTH 2048
#define STACK_TRACE_CONTEXT_LINES 3
#define MAX_ERROR_TYPE_LENGTH 128
#define MAX_SOURCE_LINE_LENGTH 2048 // Maximum length of a line in the source file

// --- Data Structures ---
typedef struct {
    bool in_error_block;
    bool print_function; // Flag to indicate if source should be printed after stack trace
    int stack_lines_shown;
    bool user_code_found_for_error;
    char current_error_type[MAX_ERROR_TYPE_LENGTH];
    char error_filename[MAX_LINE_LENGTH];
    char error_function_name[MAX_LINE_LENGTH];
    int error_line_number;
} ParseState;

// --- Global Variables ---
extern const char *USER_CODE_EXTENSIONS[];
extern const char *IGNORE_PATHS[];
extern const char *ERROR_KEYWORDS[];

// --- Function Prototypes For Mocked Functions ---
extern int (*printF)(const char*, ...);
extern FILE* (*Fopen)(const char *pathname, const char *mode);
extern bool (*find_function_start_and_brace)(FILE *file, const char *function_name, int target_line, int *out_def_line, int *out_brace_line);
extern void (*print_function_body)(FILE *file, int start_print_line, int brace_start_line, int highlight_line);

void print_function_body_(FILE *file, int start_print_line, int brace_start_line, int highlight_line);
bool find_function_start_and_brace_(FILE *file, const char *function_name, int target_line, int *out_def_line, int *out_brace_line);
bool is_valid_function_char(char c);
char *get_function_name(const char *line, char *newline);
void initialize_parse_state(ParseState *state);
bool check_start_new_error(const char *line_content, ParseState *state);
void process_stack_trace_line(const char *line_content, ParseState *state);
void process_in_error_block(const char *line_content, ParseState *state);
void process_summary_lines(const char *line_content);
void print_error_header(const char *error_type);
void print_source_function(const char *filename, const char *function_name, int line_number);
bool extract_file_and_line(const char *line, char *filename, char *function_name, int *line_number);
bool is_user_code_stack_trace(const char *line);
char *strip_valgrind_pid_prefix(char *line);
void print_leak_summary_header(void);
void print_leak_summary_line(const char *line_content, const char *summary_type);
void print_final_error_summary(const char *line_content);
void finalize_error_block(ParseState *state);
void process_log_file(FILE *file);
void print_error_summary(const char *line_content);
void print_source_line(const char *line_content, int line_number);
void print_source_line_with_highlight(const char *line_content, int line_number);

#endif  // VGP_H
