/*
 * vgp.h
 *
 * Valgrind output parser header file
 * 
 * This program parses a log file generated by Valgrind and generates a
 * more human readable version. It removes extraneous info like PIDs and
 * absolute addresses. In addition, it lists the source code for the offending
 * C/C++ function with the line causing the issue highlighted.
 * 
 * Created: 04/01/2025
 * Author : john anderson
 *
 * Copyright (C) 2025 by John Anderson <racerxr650r@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef VGP_H
#define VGP_H

// Enable POSIX.2-1992 extensions (minimum for popen()/pclose())
// Only define if not already set to a higher conformance level
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 2
#endif
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h> // For errno and strerror
#include <libgen.h> // For basename
#include <ctype.h> // For isalnum, isspace
#include <locale.h> // For setlocale

 // --- Constants ---
#define MAX_LINE_LENGTH 2048
#define STACK_TRACE_CONTEXT_LINES 20
#define MAX_ERROR_TYPE_LENGTH  2048 // Maximum length of error type string
#define MAX_SOURCE_LINE_LENGTH 2048 // Maximum length of a line in the source file

// --- Data Structures ---
typedef struct
{
    bool verbose; // Flag to indicate if verbose output is enabled
    bool print_source; // Flag to indicate if source should be printed
    bool print_stack;  // Flag to indicate if stack trace should be printed
    bool print_leak_summary; // Flag to indicate if leak summary should be printed
    char *log_file; // Path to the Valgrind log file
}AppConfig;

typedef struct {
    bool in_error_block;
    bool print_function; // Flag to indicate if source should be printed after stack trace
    int stack_lines_shown;
    bool user_code_found_for_error;
    char current_error_type[MAX_ERROR_TYPE_LENGTH];
    char error_filename[MAX_LINE_LENGTH];
    char error_function_name[MAX_LINE_LENGTH];
    int error_line_number;
    int error_count;
} ParseState;

// --- Global Variables ---
extern AppConfig app_config; // Global configuration for the application
extern const char *USER_CODE_EXTENSIONS[];
extern const char *IGNORE_PATHS[];
extern const char *ERROR_KEYWORDS[];

// --- Function Prototypes For Mocked Functions ---
bool is_valid_function_char(char c);
char *get_function_name(const char *line, char *newline);
void initialize_parse_state(ParseState *state);
bool check_start_new_error(const char *line_content, ParseState *state);
void process_stack_trace_line(const char *line_content, ParseState *state);
void process_in_error_block(const char *line_content, ParseState *state);
void process_summary_lines(const char *line_content, ParseState *state);
void print_error_header(const char *error_type, ParseState *state);
void print_source_function(const char *filename, const char *function_name, int line_number);
bool extract_file_and_line(const char *line, char *filename, char *function_name, int *line_number);
bool is_user_code_stack_trace(const char *line);
char *strip_valgrind_pid_prefix(char *line);
void print_leak_summary_line(const char *line_content, const char *summary_type);
void print_final_error_summary(const char *line_content, ParseState *state);
void finalize_error_block(ParseState *state);
void process_log_file(FILE *file);
void print_error_summary(const char *line_content);
void print_source_line(const char *line_content, int line_number);
void print_source_line_with_highlight(const char *line_content, int line_number);

#endif  // VGP_H
