/*
 * vgp.c
 *
 * Valgrind output parser
 * 
 * This program will parse a log file generated by Valgrind and generate a
 * more human readable version. It will remove extraneous info like PIDs and
 * addresses. In addition, it will list the source for the offending C/C++
 * function with the line causing the issue highlighted.
 * 
 * BTW, I hacked this together in an afternoon. So, it's a bit ugly and doesn't
 * come with any guarantees. But, it doesn't require any silly language
 * interpreters (I'm looking at you python) so it's got that ;-)
 * 
 * Created: 04/01/2025
 * Author : john anderson
 *
 * Copyright (C) 2025 by John Anderson <racerxr650r@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */ 
#include "vgp.h"

// --- Configuration ---
AppConfig app_config = {.verbose = false,
                        .print_source = false,
                        .print_stack = false,
                        .print_leak_summary = false,
                        .log_file = NULL };


const char *USER_CODE_EXTENSIONS[] = { ".c", ".cpp", ".h", ".hpp", ".C", ".CPP", ".H", ".HPP", ".cc", ".hh", ".cxx", ".hxx", ".f90", ".f", ".F", ".ada", ".ads", ".adb", NULL };
const char *IGNORE_PATHS[] = { "/usr/", "/lib/", "vg_", NULL };
const char *ERROR_KEYWORDS[] = {
    "Invalid read", "Invalid write",
    "depends on uninitialised value",
    "Invalid free", "Mismatched free",
    "Source and destination overlap",
    "Invalid usage of address",
    NULL
};

// --- Helper Functions ---
// Checks if a line is likely part of a user code stack trace.
bool is_user_code_stack_trace(const char *line)
{
    if(line == NULL)
        return false; // Invalid pointer
        
    // Check for stack trace indentation
    if (strncmp(line, "   at ", 6) != 0 && strncmp(line, "   by ", 6) != 0)
    {
        return false;
    }

    // Check for user code file extensions
    bool found_user_extension = false;
    for (int i = 0; USER_CODE_EXTENSIONS[i] != NULL; ++i)
    {
        if (strstr(line, USER_CODE_EXTENSIONS[i]) != NULL)
        {
            found_user_extension = true;
            break;
        }
    }
    if (!found_user_extension)
    {
        return false;
    }

    // Check if the path should be ignored
    for (int i = 0; IGNORE_PATHS[i] != NULL; ++i)
    {
        if (strstr(line, IGNORE_PATHS[i]) != NULL)
        {
            return false;
        }
    }

    return true;
}

// Removes the Valgrind PID prefix from a line.
char *strip_valgrind_pid_prefix(char *line)
{
    if(line == NULL)
        return NULL; // Invalid pointer
    
    // Locate the first occurrence of "=="
    char *prefix_end = strstr(line, "==");
    if(prefix_end == NULL)  
        return line; // No prefix found, return original line
    prefix_end += 2; // Move past "=="

    // Skip whitespace after "=="
    while(isspace((unsigned char)*prefix_end))
        prefix_end++;

    // Check if the prefix is followed by digits
    if (isdigit((unsigned char)*prefix_end))
    {
        // Find the end of the digits
        while (isdigit((unsigned char)*prefix_end))
            prefix_end++;
    }
    else
        return line; // No digits found, return original line

    // Skip whitespace after digits
    while(isspace((unsigned char)*prefix_end))
        prefix_end++;

    // Check for "== " after the digits
    if (strncmp(prefix_end, "== ", 3) != 0)
        return line; // No "==" found, return original line
    prefix_end += 3; // Move past "=="

    // Skip whitespace after "=="
//    while(isspace((unsigned char)*prefix_end) || *prefix_end == '\n')
//        prefix_end++;

    return prefix_end; // Return pointer to the start of the message
}

// Get just the function name, filename, and line number from a Valgrind stack trace line
char *get_function_name(const char *line, char *newline)
{
    char function[MAX_LINE_LENGTH] = "?";
    char filename[MAX_LINE_LENGTH] = "?";
    int line_number = 0;
    int length = strlen(line);
    
    // Read the input line
    sscanf(line,"%*s %*s %[^ ] (%[^:]:%d)",(char *)function, (char *)filename, &line_number);

    // Strip of any parenthesis/parameters at the end of the function name
    size_t len = strlen(function);
    // Find the first opening parenthesis
    char *first_open_paren = strchr(function, '(');
    // If an open paren was found...
    if (first_open_paren != NULL)
        if (first_open_paren < (function + len - 1))
            *first_open_paren = '\0';
    
    // Create the output line
    if(line_number)
        snprintf(newline,length,"%s(%s:%d)\n",function,basename(filename),line_number);
    else
        snprintf(newline,length,"?(?:0)\n");

    return(newline);
}

// Prints an error block header.
void print_error_header(const char *error_type, ParseState *state)
{
    printf("----------------------------------------\n");
    printf("[ERROR #%d] ", ++state->error_count);
    if(error_type[strlen(error_type) - 1] == '\n')
        printf("%s", error_type);
    else
        printf("%s\n", error_type);
    if(app_config.print_stack || app_config.verbose)
        printf("Call Stack:\n");
}

// Prints a leak summary line.
void print_leak_summary_line(const char *line, const char *leak_type)
{
    int bytes = 0, blocks = 0;
    if (sscanf(line, "%*[^:]: %'d %*s %*s %'d", &bytes, &blocks) == 2)
    {
        printf("* %s: %d bytes in %d blocks\n", leak_type, bytes, blocks);
    }
    else
    {
        if(line[strlen(line) - 1] == '\n')
            printf("%s", line); // Print raw if parse fails
        else
            printf("%s\n", line); // Print raw if parse fails
    }
}

// Prints the final error count summary.
void print_final_error_summary(const char *line, ParseState *state)
{
    int error_count = 0;
    if (sscanf(line, "%*[^:]: %'d", &error_count) == 1)
    {
        printf("\n--- FINAL COUNTS ---\n");
        printf("* Total Errors: %d\n", state->error_count);
        printf("* Possible Leaks: %d\n", error_count - state->error_count);
    }
    else
    {
        if(line[strlen(line) - 1] == '\n')
            printf("%s", line); // Print raw if parse fails
        else
            printf("%s\n", line); // Print raw if parse fails
    }
}

// Extracts the filename, function name, and line number from a stack trace line.
bool extract_file_and_line(const char *line, char *filename, char *function_name, int *line_number)
{
    if(line == NULL || filename == NULL || function_name == NULL || line_number == NULL)
    {
        return false; // Invalid arguments
    }

    char temp_filename[MAX_LINE_LENGTH];
    char temp_function[MAX_LINE_LENGTH];
    // Attempt to parse the line with function name
//    if (sscanf(line, "%*[^:]: %[^(]( %[^:]:%d)", (char *)temp_function, (char *)temp_filename, line_number) == 3)
    if (sscanf(line, "%*s %*s %[^ ] (%[^:]:%d)", (char *)temp_function, (char *)temp_filename, line_number) == 3)
    {
        char *filename_ptr = strtok(temp_filename, " \t"); // Remove leading whitespace
        filename_ptr = strtok(filename_ptr, " \t"); // Remove trailing whitespace
        strcpy(filename, filename_ptr);

        char *functionname_ptr = strtok(temp_function, " \t"); // Remove leading whitespace
        functionname_ptr = strtok(functionname_ptr, " \t"); // Remove trailing newline
        strcpy(function_name, functionname_ptr);

        // Strip of any parenthesis/parameters at the end of the function name
        size_t len = strlen(function_name);
        // Find the first opening parenthesis
        char *first_open_paren = strchr(function_name, '(');
        // If an open paren was found...
        if (first_open_paren != NULL)
            if (first_open_paren < (function_name + len - 1))
                *first_open_paren = '\0';
        // If a period is included in the function name, lop it off
        char *period = strchr(function_name, '.');
        // If an open paren was found...
        if (period != NULL)
            if (period < (function_name + len - 1))
                *period = '\0';

        return true;
    }
    // Attempt to parse the line without function name
    else if (sscanf(line, "%*[^:]: %[^:]:%d", (char *)temp_filename, line_number) == 2)
    {
        strcpy(filename, temp_filename); // Fallback if basename fails
        strcpy(function_name, ""); // No function name available
        return true;
    }
    // Attempt to parse a line without line number
    else if (sscanf(line, "%*[^:]: %[^(](in %[^)])", (char *)temp_function, (char *)temp_filename) == 2)
    {
        char *filename_ptr = strtok(temp_filename, " \t"); // Remove leading whitespace
        filename_ptr = strtok(filename_ptr, " \t"); // Remove trailing whitespace
        strcpy(filename, filename_ptr);

        char *functionname_ptr = strtok(temp_function, " \t"); // Remove leading whitespace
        functionname_ptr = strtok(functionname_ptr, " \t"); // Remove trailing newline
        strcpy(function_name, functionname_ptr);

        *line_number = 0; // No line number available
        return true;
    }
    return false;
}

// Function to execute a shell command and capture its output
bool execute_command(const char *command, char *output, size_t output_size)
{
    if (command == NULL || output == NULL || output_size == 0)
        return false; // Invalid arguments

    FILE *fp = popen(command, "r");

    if (fp == NULL)
    {
        perror("popen");
        return false;
    }

    if (fgets(output, output_size, fp) == NULL)
    {
        if (ferror(fp))
        {
            perror("fgets");
            pclose(fp);
            return false;
        }
    }

    pclose(fp);
    return true;
}

bool parse_ctags_output(const char *ctags_output, int *start_line, int *end_line)
{
    // Check for NULL pointers
    if (ctags_output == NULL || start_line == NULL || end_line == NULL)
    {
        fprintf(stderr, "Error: Invalid arguments to parse_ctags_output.\n");
        return false;
    }

    // Find the start line
    char *input = strstr(ctags_output, "line:");
    if (input == NULL)
    {
        fprintf(stderr, "Error: Invalid ctags output format.\n");
        return false;
    }
    sscanf(input, "line:%d", start_line);

    // Find the end line
    input = strstr(input, "end:");
    if (input == NULL)
    {
        fprintf(stderr, "Error: Invalid ctags output format.\n");
        return false;
    }
    sscanf(input, "end:%d", end_line);

    // Check if the start and end lines are valid
    if (*start_line <= 0 || *end_line <= 0 || *start_line >= *end_line)
    {
        fprintf(stderr, "Error: Invalid line range in ctags output (start: %d, end: %d).\n", *start_line, *end_line);
        return false;
    }
    return true;
}

// Prints the source code of the entire function containing the given line number.
void print_source_function(const char *source_file, const char *function_name, int line_number)
{
    if (source_file == NULL || function_name == NULL || line_number <= 0)
    {
        fprintf(stderr, "Error: Invalid arguments to print_source_function.\n");
        return;
    }

    char command[MAX_LINE_LENGTH];
    char ctags_output[MAX_LINE_LENGTH];
    int start_line = 0, end_line = 0;

    // Generate ctags command to find the function's start and end lines
    snprintf(command, sizeof(command),
             "ctags -o - --c-kinds=f --fields=+ne %s | grep '^%s'", source_file, function_name);

    if (!execute_command(command, ctags_output, sizeof(ctags_output))) 
    {
        fprintf(stderr, "Error: Could not find function '%s' in file '%s'.\n", function_name, source_file);
        return;
    }

    // Parse the ctags output to extract the start and end lines
    if (!parse_ctags_output(ctags_output, &start_line, &end_line))
    {
        fprintf(stderr, "Error: Failed to parse ctags output for function '%s'.\n", function_name);
        return;
    }

    if (start_line <= 0 || ++end_line <= 0 || start_line > end_line)
    {
        fprintf(stderr, "Error: Invalid line range for function '%s' (start: %d, end: %d).\n",
                function_name, start_line, end_line);
        return;
    }

    // Open the source file to extract the function's code
    FILE *file = fopen(source_file, "r");
    if (file == NULL)
    {
        perror("fopen");
        return;
    }

    char line[MAX_LINE_LENGTH];
    int current_line = 1;

    // Forward to the start line
    while (current_line++ < start_line && fgets(line, sizeof(line), file));

    // Print the function's code with line number and offending line marked from start to end line
    while (current_line++ <= end_line && fgets(line, sizeof(line), file)) 
        printf("%c%4d %s", current_line==line_number?'>':' ', current_line, line);

    fclose(file);
}

// --- Core Parsing Logic ---
// Initializes the parsing state
void initialize_parse_state(ParseState *state)
{
    if(state != NULL)
    {
        state->in_error_block = false;
        state->print_function = false;
        state->stack_lines_shown = 0;
        state->user_code_found_for_error = false;
        state->current_error_type[0] = '\0';
        state->error_filename[0] = '\0';
        state->error_function_name[0] = '\0';
        state->error_line_number = -1;
        state->error_count = 0;
    }
}

// Checks if the line marks the start of a new error block
bool check_start_new_error(const char *line_content, ParseState *state)
{
    if (line_content == NULL || state == NULL)
        return false; // Invalid arguments

    if (!state->in_error_block)
    {
        for (int i = 0; ERROR_KEYWORDS[i] != NULL; ++i)
        {
            if (strstr(line_content, ERROR_KEYWORDS[i]))
            {
                print_error_header(line_content, state);
                strncpy(state->current_error_type, ERROR_KEYWORDS[i], sizeof(state->current_error_type) - 1);
                state->current_error_type[sizeof(state->current_error_type) - 1] = '\0';
                state->in_error_block = true;
                state->stack_lines_shown = 0;
                state->user_code_found_for_error = false;
                state->print_function = false; // Reset print flag for new error
                return true; // New error detected
            }
        }
    }
    return false; // Not the start of a new error
}

// Processes a line identified as part of a stack trace
void process_stack_trace_line(const char *line_content, ParseState *state)
{
    if(line_content == NULL || state == NULL)
        return; // Invalid arguments

    if (state->stack_lines_shown < STACK_TRACE_CONTEXT_LINES || is_user_code_stack_trace(line_content))
    {
        char stack_entry[MAX_LINE_LENGTH];
        if(app_config.print_stack || app_config.verbose)
        {
            printf("  - %s", get_function_name((const char*)line_content, stack_entry)); // Cast needed for get_function_name prototype
            state->stack_lines_shown++;
        }

        if (!state->user_code_found_for_error && is_user_code_stack_trace(line_content))
        {
            state->user_code_found_for_error = true;
            // Extract file/line and set flag to print source later
            state->print_function = extract_file_and_line(line_content, state->error_filename, state->error_function_name, &state->error_line_number);
        }
    }
    else if (!state->user_code_found_for_error && state->stack_lines_shown == STACK_TRACE_CONTEXT_LINES)
    {
        if(app_config.print_stack || app_config.verbose)
        {
            // Print ellipsis only once after context lines if no user code found yet
            printf("  - ...\n");
            state->stack_lines_shown++; // Increment to prevent printing ellipsis again
        }
    }
}

// Finalizes the processing of an error block (prints source, resets state)
void finalize_error_block(ParseState *state)
{
    if (state == NULL)
        return; // Invalid arguments

    if (!state->user_code_found_for_error && state->stack_lines_shown > 0)
    {
        printf("  (-> Check stack trace above for user code related to '%s')\n", state->current_error_type);
    }
    if (state->print_function)
    {
        printf("Source (%s:%d)\n", state->error_filename, state->error_line_number);
        if(app_config.print_source || app_config.verbose)
        {
            print_source_function(state->error_filename, state->error_function_name, state->error_line_number);
            printf("\n");
        }
    }
    // Reset state for the next block (or end of file)
    state->in_error_block = false;
    state->print_function = false;
    // No need to print the separator here, let the next error header do it or handle at EOF.
}

// Processes lines within an active error block
void process_in_error_block(const char *line_content, ParseState *state)
{
    if (line_content == NULL || state == NULL)
        return; // Invalid arguments
    
    if (strncmp(line_content, "   at ", 6) == 0 || strncmp(line_content, "   by ", 6) == 0)
    {
        process_stack_trace_line(line_content, state);
    }
    else
    {
        // Line is not a stack trace line, signifies end of the current error's stack trace
        finalize_error_block(state);
        // Note: We might need to re-process this line if it's a summary line or start of a new error
        // This refactoring assumes error blocks are separated by non-stack-trace lines or EOF.
    }
}

// Checks for and processes summary lines (Leak or Final)
void process_summary_lines(const char *line_content, ParseState *state)
{
    if (line_content == NULL)
        return; // Invalid arguments

    if (strstr(line_content, "LEAK SUMMARY:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            printf("\n--- LEAK SUMMARY ---\n");
    }
    else if (strstr(line_content, "definitely lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Definitely Lost");
    }
    else if (strstr(line_content, "indirectly lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Indirectly Lost");
    }
    else if (strstr(line_content, "possibly lost:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Possibly Lost");
    }
    else if (strstr(line_content, "still reachable:"))
    {
        if(app_config.print_leak_summary || app_config.verbose)
            print_leak_summary_line(line_content, "Still Reachable");
    }
    else if (strstr(line_content, "ERROR SUMMARY:"))
    {
        print_final_error_summary(line_content, state);
    }
}

// Processes the entire log file
void process_log_file(FILE *file)
{
    if (file == NULL)
        return; // Invalid file pointer

    char line[MAX_LINE_LENGTH];
    ParseState state;
    initialize_parse_state(&state);

    while (fgets(line, sizeof(line), file))
    {
        char *line_content = strip_valgrind_pid_prefix(line);

        // Skip empty or whitespace-only lines *unless* inside an error block
        // (empty lines can sometimes terminate an error block in Valgrind output)
        if (!state.in_error_block && strspn(line_content, " \t\n\r") == strlen(line_content))
        {
            continue;
        }

        // If we are in an error block, process the line accordingly
        if (state.in_error_block)
        {
            process_in_error_block(line_content, &state);
            // If finalize_error_block was called, state.in_error_block is now false.
            // We continue to the summary check below for the same line.
        }

        // Check if the line starts a *new* error block (only if not currently in one)
        // Or if the previous block was just finalized.
        if (!state.in_error_block)
        {
            bool new_error_started = check_start_new_error(line_content, &state);
            if (new_error_started)
            {
                continue; // Skip summary checks if it's the start of an error
            }
        }

        // Check for summary lines (Leak or Final) if not inside an error block
        if (!state.in_error_block)
        {
             process_summary_lines(line_content, &state);
        }
    }

    // Handle the case where the file ends while still inside an error block
    if (state.in_error_block)
    {
        finalize_error_block(&state); // Print source if needed
        printf("----------------------------------------\n\n"); // Add final separator
    }
}
